### ISSUE TITLE
post user endpoint does not check for username

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/backend#34]
## Summary
It is possible to create a new user with the same username, effectively this will overwrite an existing user

## expected
Error upon posting a user with the same username as already existing

## actual
User is overwritten

## additional info
This bug has been found while reviewing PR #33, it's possible that the changes to the UserTable are responsible for this.

**Comment by larsuzh** [comment]
I'm uncertain, but it seems like the updates made in backend #7 altered the database schema, shifting the primary key from using user_id to a new primary key structure with a partition key (though I'm unsure what values are being passed here) and the username as the search key. I assume this means that usernames must now be unique. However, as the post_user_to_db function in the UserRepository wasn't adjusted to reflect these changes, it now verifies the username instead of the user_id and updates the value since it only checks for the existence of user_id.
<img width="767" alt="image" src="https://github.com/uzh-ase-fs24/backend/assets/91185670/ba07e015-f1e9-4b08-8dc1-b39de54bc72f">

**Comment by v4lentin1879** [comment]
Fixed in [ff0256c](https://github.com/uzh-ase-fs24/backend/commit/ff0256c2b9365ebc12cd532583fb6dd8a270c10d), @lars-boesch can you confirm?
